language: python
python:
- '3.8'
before_install:
- openssl aes-256-cbc -K $encrypted_3fb356561302_key -iv $encrypted_3fb356561302_iv
  -in tests/files.enc -out tests/files.tar -d
- tar xf tests/files.tar -C tests/
- python --version
- pip install -U pip
- pip install codecov
install:
- pip install '.[mupdf,test]'
script: pytest
after_success:
- codecov
